from typing import Dict
from jinja2 import Environment, BaseLoader

HTML_TEMPLATE = """
<!doctype html>
<html>
<head>
  <meta charset='utf-8'>
  <title>{{ title }}</title>
  <style>
    body { font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif; padding: 24px; }
    h1 { margin: 0 0 8px 0; }
    .meta { color: #555; margin-bottom: 16px; }
    .card { border:1px solid #e5e7eb; border-radius:12px; padding:16px; margin-bottom:12px; }
    .grid { display:grid; grid-template-columns: 1fr 1fr; gap:12px; }
    .muted { color:#6b7280; }
  </style>
</head>
<body>
  <h1>{{ company_name }}</h1>
  <div class="meta">{{ company_address }}</div>
  <h2>{{ title }}</h2>

  <div class="grid">
    <div class="card"><strong>Site</strong><br>{{ rec.site }}</div>
    <div class="card"><strong>Date</strong><br>{{ rec.date_iso }}</div>
    <div class="card"><strong>Crew Size</strong><br>{{ rec.crew_size }}</div>
    <div class="card"><strong>Confined Space</strong><br>{{ 'Yes' if rec.confined_space else 'No' }}</div>
    {% if rec.attendant %}
    <div class="card"><strong>Attendant</strong><br>{{ rec.attendant }}</div>
    {% endif %}
  </div>

  <div class="card"><strong>Materials</strong><div class="muted">{{ rec.materials or '-' }}</div></div>
  <div class="card"><strong>Hazards</strong><div class="muted">{{ rec.hazards or '-' }}</div></div>

  <p class="muted">Generated by 007 Safety.</p>
</body>
</html>
"""

def render_html(context: Dict) -> str:
    env = Environment(loader=BaseLoader())
    tpl = env.from_string(HTML_TEMPLATE)
    return tpl.render(**context)


def try_html_to_pdf_bytes(html: str) -> bytes | None:
    try:
        from weasyprint import HTML  # type: ignore
    except Exception:
        return None
    pdf = HTML(string=html).write_pdf()
    return pdf
